apiVersion: v1
kind: Service
metadata:
  name: recommend-load-balancer
spec:
  selector:
    app: recommend
  ports:
    - protocol: TCP
      port: 8082  # Service port
      targetPort: 8082  # Pod port
  type: LoadBalancer
